typedef struct{
	unsigned char filename[8];
	unsigned char ext[3];
	unsigned char attributes;
	unsigned char reserved[10];
	unsigned short modify_time;
	unsigned short modify_date;
	unsigned short starting_cluster;
	unsigned int file_size;
}__attribute((packed))FatEntry;

typedef struct {
    unsigned char jmp[3];
    char oem[8]; 
    unsigned short sector_size; 
    unsigned char sectors_per_cluster; 
    unsigned short reserved_sectors; 
    unsigned char number_of_fats; 
    unsigned short root_dir_entries; 
    unsigned short total_sector_short;
    unsigned char media_descriptor;
    unsigned short fat_size_sectors;
    unsigned short sectors_per_track; 
    unsigned short number_of_heads;
    unsigned int hidden_sectors;
    unsigned int total_sector_int;
    unsigned int sectors_per_fat;
    unsigned short mirror_flags; 
    unsigned short filesystem_version;
    unsigned int first_cluster; 
    unsigned short filesystem_information;
    unsigned short backup_boot_sector_location; 
    char reserved[10];
    unsigned char logical_drive_number; 
    unsigned char current_head; 
    unsigned char extended_signature;
    unsigned int serial_number_partition; 
    char volume_label[11]; 
    char filesystem_type[8]; 
    char boot_code[420]; 
    unsigned short boot_sector_signature;
} __attribute((packed)) Fat32BootSector;
